[theme]
primaryColor = "#52B788"
backgroundColor = "#F4FFF8"
secondaryBackgroundColor = "#E8F8EE"
textColor = "#1B4332"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "viewer"

[logger]
level = "info"

[browser]
gatherUsageStats = false
